// Code generated by "enumer -type=state -trimprefix=state -transform=kebab-case"; DO NOT EDIT.

package tui

import (
	"fmt"
)

const _stateName = "ExtensionSelectSearchSearchResultsLayerActionSelectMediaInfoLoadingError"

var _stateIndex = [...]uint8{0, 15, 21, 34, 39, 51, 60, 67, 72}

func (i state) String() string {
	i -= 1
	if i < 0 || i >= state(len(_stateIndex)-1) {
		return fmt.Sprintf("state(%d)", i+1)
	}
	return _stateName[_stateIndex[i]:_stateIndex[i+1]]
}

var _stateValues = []state{1, 2, 3, 4, 5, 6, 7, 8}

var _stateNameToValueMap = map[string]state{
	_stateName[0:15]:  1,
	_stateName[15:21]: 2,
	_stateName[21:34]: 3,
	_stateName[34:39]: 4,
	_stateName[39:51]: 5,
	_stateName[51:60]: 6,
	_stateName[60:67]: 7,
	_stateName[67:72]: 8,
}

// stateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func stateString(s string) (state, error) {
	if val, ok := _stateNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to state values", s)
}

// stateValues returns all values of the enum
func stateValues() []state {
	return _stateValues
}

// IsAstate returns "true" if the value is listed in the enum definition. "false" otherwise
func (i state) IsAstate() bool {
	for _, v := range _stateValues {
		if i == v {
			return true
		}
	}
	return false
}
